import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import TopNav from "./_components/topnav";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by me",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <ClerkProvider>
        <body className="flex flex-col gap-4">
          <TopNav />
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
